from datetime import datetime, timezone
from enum import Enum

from pydantic import BaseModel, Field


class EventType(str, Enum):
    THOUGHT = "thought"
    ACTION = "action"
    OBSERVATION = "observation"
    ERROR = "error"
    FINAL = "final"


class BaseEvent(BaseModel):
    """
    Base class for all events generated by the agent.
    """
    type: EventType
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

class ThoughtEvent(BaseEvent):
    type: EventType = EventType.THOUGHT
    thought: str
    
class ActionEvent(BaseEvent):
    type: EventType = EventType.ACTION
    tool: str
    tool_input: str
    
class ObservationEvent(BaseEvent):
    type: EventType = EventType.OBSERVATION
    observation: str
    
class ErrorEvent(BaseEvent):
    type: EventType = EventType.ERROR
    error: str
    
class FinalAnswerEvent(BaseEvent):
    type: EventType = EventType.FINAL
    answer: str

